// The frozen scenarios are valid inputs, current with their source, and their expectations are internally consistent:
// the expected payload hashes to the trace's result.hash, and the trace's snapshot_digest is the digest of the committed
// snapshot. The digest is recomputed with the TypeScript assembler's exported function, so an expectation generated by
// the Python reference is checked against a second implementation of RFC 8785 here.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { test } from 'node:test';
import { snapshotDigest } from '@contextwindowarchitecture/assembler';
import { buildScenarios } from '../scripts/build-scenarios.mjs';
import { ROOT } from '../src/harness/adapters.mjs';
import { loadScenarios } from '../src/harness/cases.mjs';
import { problems, validateSnapshot, validateTrace } from '../src/harness/schemas.mjs';

const scenarios = await loadScenarios(path.join(ROOT, 'scenarios'));

test('there are scenarios, each with both renderings', () => {
  assert.ok(scenarios.length >= 5, 'the basic stage has five steps');
  for (const scenario of scenarios) assert.deepEqual(scenario.variants.map(v => v.name), ['fixture', 'messages'], scenario.id);
});

test('the generated snapshots are current with scenarios/basic/source', async () => {
  const built = await buildScenarios();
  for (const [id, { files }] of Object.entries(built)) {
    for (const [name, content] of Object.entries(files)) {
      assert.equal(await readFile(path.join(ROOT, 'scenarios', 'basic', id, name), 'utf8'), content, `${id}/${name} is stale: run pnpm run scenarios:build`);
    }
  }
});

for (const scenario of scenarios) {
  test(`${scenario.id}: scenario.json names the step, what it proves and where its expectations came from`, () => {
    const { meta } = scenario;
    for (const field of ['id', 'step', 'title', 'question', 'description', 'proves', 'look_for', 'budget', 'expectations']) assert.ok(field in meta, field);
    assert.equal(meta.id, path.basename(scenario.id));
    assert.equal(typeof meta.expectations.reviewed, 'boolean');
  });

  for (const variant of scenario.variants) {
    const label = `${scenario.id} ${variant.name}`;
    const snapshot = JSON.parse(variant.snapshot.toString('utf8'));

    test(`${label}: the snapshot validates against snapshot.schema.json`, () => {
      assert.ok(validateSnapshot(snapshot), problems(validateSnapshot).join('; '));
    });

    test(`${label}: the expectation is present, valid, and consistent with the snapshot`, () => {
      assert.ok(variant.expected, `no expected trace: run pnpm run expect --from python`);
      const { payload, trace } = variant.expected;
      assert.ok(validateTrace(trace), problems(validateTrace).join('; '));
      assert.equal(trace.context.snapshot_digest, snapshotDigest(snapshot), 'the expected trace is for another snapshot');
      assert.equal(trace.profile.id, snapshot.profile.id);
      assert.deepEqual(trace.budget, snapshot.budget);
      if (trace.refused.bool) {
        assert.equal(payload, null, 'a refusal has no payload');
        assert.equal(trace.result, null);
      } else {
        assert.ok(payload, 'an assembled expectation has a payload file');
        assert.equal(createHash('sha256').update(payload).digest('hex'), trace.result.hash, 'expected.payload.txt does not hash to result.hash');
      }
      for (const code of scenario.meta.look_for) {
        const seen = trace.excluded.some(row => row.reason === code) || trace.refused.reason === code;
        assert.ok(seen, `look_for names ${code}, but the expected trace does not record it`);
      }
    });
  }
}
