#!/usr/bin/env node
// The comparison harness. One frozen snapshot in, every assembler's payload and trace out, compared byte for byte
// and field for field with the expectation and with each other.
//
//   cwa-demo run <snapshot.json> [--assembler python,typescript,go] [--json]
//   cwa-demo compare [scenarios] [--assembler ...] [--json]
//   cwa-demo expect --from <assembler> [scenarios]
//   cwa-demo conformance [--assembler ...] [--dir vendor/cwa/conformance]
import { existsSync } from 'node:fs';
import { readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadAssemblers, ROOT, runAll, select } from './adapters.mjs';
import { loadConformance, loadScenarios } from './cases.mjs';
import { agreement, comparable, compareResult } from './compare.mjs';

const USAGE = `usage:
  cwa-demo run <snapshot.json> [--assembler a,b] [--json]      one snapshot through the assemblers
  cwa-demo compare [scenarios] [--assembler a,b] [--json]      every scenario against its expectation and the others
  cwa-demo expect --from <assembler> [scenarios]                write expected payloads and traces from one assembler
  cwa-demo conformance [--assembler a,b] [--dir <conformance>]  the vendored conformance cases: the harness's self-check
`;

function parseArgs(argv) {
  const flags = { assembler: [], json: false }, positional = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--json') flags.json = true;
    else if (arg === '--assembler' || arg === '--from' || arg === '--dir') flags[arg.slice(2)] = argv[++i];
    else if (arg.startsWith('--')) throw new Error(`unknown flag ${arg}`);
    else positional.push(arg);
  }
  if (typeof flags.assembler === 'string') flags.assembler = flags.assembler.split(',').filter(Boolean);
  return { command: positional[0], positional: positional.slice(1), flags };
}

/** Run `work` over `items` with at most `limit` in flight, keeping order. */
async function mapLimit(items, limit, work) {
  const results = new Array(items.length);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (next < items.length) { const index = next++; results[index] = await work(items[index], index); }
  }));
  return results;
}

const pad = (text, width) => String(text).padEnd(width);
const table = rows => {
  const widths = rows[0].map((_, column) => Math.max(...rows.map(row => String(row[column]).length)));
  return rows.map(row => row.map((cell, column) => pad(cell, widths[column])).join('  ').trimEnd()).join('\n');
};

const summarize = result => {
  if (result.outcome === 'assembled') return `assembled ${result.trace.result.input_tokens} tokens, hash ${result.trace.result.hash.slice(0, 12)}`;
  if (result.outcome === 'refused') return `refused: ${result.trace.refused.reason}`;
  return `${result.outcome}: ${result.detail}`;
};

async function run({ positional, flags }, assemblers) {
  const [file] = positional;
  if (!file) throw new Error('run needs a snapshot file');
  const bytes = await readFile(file);
  const results = await runAll(select(assemblers, flags.assembler), bytes);
  const agree = agreement(results);
  if (flags.json) {
    console.log(JSON.stringify({ results: results.map(r => ({ ...r, payload: r.payload === undefined ? undefined : r.payload && r.payload.toString('utf8') })), agreement: agree }, null, 2));
    return agree.agree ? 0 : 1;
  }
  for (const result of results) console.log(`${pad(result.assembler, 11)} ${summarize(result)} (${result.durationMs} ms)`);
  console.log(agree.agree ? 'agreement: every assembler agrees' : `agreement: NO\n${agree.differences.map(d => `  ${d.assembler} vs ${d.against}: ${d.detail}`).join('\n')}`);
  const shown = results.find(r => r.outcome === 'assembled');
  if (shown) console.log(`\n--- payload (${shown.assembler}) ---\n${shown.payload.toString('utf8')}`);
  return agree.agree ? 0 : 1;
}

async function compare({ positional, flags }, assemblers) {
  const dir = path.resolve(positional[0] ?? path.join(ROOT, 'scenarios'));
  const chosen = select(assemblers, flags.assembler);
  const scenarios = await loadScenarios(dir);
  if (scenarios.length === 0) throw new Error(`no scenarios under ${dir}`);
  const rows = [], report = [];
  let failures = 0;
  for (const scenario of scenarios) {
    for (const variant of scenario.variants) {
      const results = await runAll(chosen, variant.snapshot);
      const agree = agreement(results);
      const judged = results.map(result => ({ assembler: result.assembler, ...(variant.expected ? compareResult(result, variant.expected) : { outcome: 'no expectation' }) }));
      const expectation = variant.expected
        ? `${scenario.meta.expectations?.generated_by ? `generated by ${scenario.meta.expectations.generated_by}` : 'expected files'}${scenario.meta.expectations?.reviewed ? ', reviewed' : ', UNREVIEWED'}`
        : 'none';
      failures += judged.filter(j => j.outcome === 'failed').length + (agree.agree ? 0 : 1);
      report.push({ scenario: scenario.id, variant: variant.name, results: judged, agreement: agree, expectation });
      rows.push([scenario.id, variant.name, ...judged.map(j => j.outcome), agree.agree ? 'agree' : 'DISAGREE', expectation]);
      for (const j of judged) if (j.detail && j.outcome !== 'skipped') rows.push(['', '', ...judged.map(x => (x === j ? `  ${j.detail}` : '')), '', '']);
      for (const d of agree.differences) rows.push(['', '', ...judged.map(() => ''), `  ${d.assembler} vs ${d.against}: ${d.detail}`, '']);
    }
  }
  if (flags.json) console.log(JSON.stringify(report, null, 2));
  else console.log(table([['scenario', 'variant', ...Object.keys(chosen), 'agreement', 'expectation'], ...rows]));
  return failures === 0 ? 0 : 1;
}

async function expect({ positional, flags }, assemblers) {
  if (!flags.from) throw new Error('expect needs --from <assembler>');
  const dir = path.resolve(positional[0] ?? path.join(ROOT, 'scenarios'));
  const [assembler] = Object.values(select(assemblers, [flags.from]));
  const scenarios = await loadScenarios(dir);
  if (scenarios.length === 0) throw new Error(`no scenarios under ${dir}`);
  for (const scenario of scenarios) {
    let changed = false;
    for (const variant of scenario.variants) {
      const [result] = await runAll({ [assembler.id]: assembler }, variant.snapshot);
      if (result.outcome !== 'assembled' && result.outcome !== 'refused') {
        throw new Error(`${scenario.id} ${variant.name}: ${assembler.id} ${result.outcome}: ${result.detail}`);
      }
      const trace = { ...comparable(result.trace), trace_id: `${scenario.id}:${variant.name}` };
      const traceText = JSON.stringify(trace, null, 2) + '\n';
      const before = existsSync(variant.files.trace) ? await readFile(variant.files.trace, 'utf8') : null;
      const payloadBefore = existsSync(variant.files.payload) ? await readFile(variant.files.payload) : null;
      const payloadSame = (payloadBefore === null && result.payload === null) || (payloadBefore !== null && result.payload !== null && payloadBefore.equals(result.payload));
      if (before === traceText && payloadSame) { console.log(`${scenario.id} ${variant.name}: unchanged`); continue; }
      await writeFile(variant.files.trace, traceText);
      if (result.payload === null) { if (payloadBefore !== null) await unlink(variant.files.payload); }
      else await writeFile(variant.files.payload, result.payload);
      changed = true;
      console.log(`${scenario.id} ${variant.name}: ${summarize(result)}`);
    }
    const metaFile = path.join(scenario.dir, 'scenario.json');
    const meta = JSON.parse(await readFile(metaFile, 'utf8'));
    const wasReviewed = meta.expectations?.reviewed === true;
    const expectations = { generated_by: assembler.id, reviewed: wasReviewed && !changed };
    if (JSON.stringify(meta.expectations) !== JSON.stringify(expectations)) {
      meta.expectations = expectations;
      await writeFile(metaFile, JSON.stringify(meta, null, 2) + '\n');
      if (wasReviewed && changed) console.log(`${scenario.id}: expectations changed, so reviewed is now false`);
    }
  }
  return 0;
}

/** The vendored conformance cases through every chosen assembler: passed, failed, skipped and rejected counts, with
 * every failure's detail. Exits 1 on any failure, like the reference runner. */
async function conformance({ flags }, assemblers) {
  const dir = path.resolve(flags.dir ?? path.join(ROOT, 'vendor', 'cwa', 'conformance'));
  const chosen = select(assemblers, flags.assembler);
  const { cases, rejections } = await loadConformance(dir);
  const outcomes = await mapLimit([...cases, ...rejections], 4, async item => {
    const results = await runAll(chosen, item.snapshot);
    return { id: item.id, judged: results.map(result => ({ assembler: result.assembler, ...compareResult(result, item.expected) })) };
  });
  let failures = 0;
  const lines = [];
  for (const assembler of Object.keys(chosen)) {
    const count = (want, items) => items.filter(item => item.judged.find(j => j.assembler === assembler).outcome === want).length;
    const caseRows = outcomes.slice(0, cases.length), rejectionRows = outcomes.slice(cases.length);
    const failed = outcomes.filter(item => item.judged.find(j => j.assembler === assembler).outcome === 'failed');
    failures += failed.length;
    lines.push(`${pad(assembler, 11)} ${count('passed', caseRows)}/${cases.length} cases passed, ${count('rejected', rejectionRows)}/${rejections.length} rejection snapshots rejected` +
      `${count('skipped', outcomes) ? `, ${count('skipped', outcomes)} skipped` : ''}${failed.length ? `, ${failed.length} FAILED` : ''}`);
    for (const item of failed) lines.push(`  ${item.id}: ${item.judged.find(j => j.assembler === assembler).detail}`);
  }
  if (flags.json) console.log(JSON.stringify(outcomes, null, 2));
  else console.log(lines.join('\n'));
  return failures === 0 ? 0 : 1;
}

const COMMANDS = { run, compare, expect, conformance };

async function main(argv) {
  const parsed = parseArgs(argv);
  const command = COMMANDS[parsed.command];
  if (!command) { console.error(USAGE); return 2; }
  const assemblers = await loadAssemblers();
  return command(parsed, assemblers);
}

main(process.argv.slice(2)).then(code => { process.exitCode = code; }, error => { console.error(error.message); process.exitCode = 2; });
